apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: openfaas-fn
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: openfaas-fn
  name: pod-reader-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: openfaas-fn
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
