apiVersion: v1
# Indicates this as a service
kind: Service
metadata:
 # Service name
 name: cache-controller
spec:
 selector:
   # Selector for Pods
   app: cache-controller
 ports:
   # Port Map
 - port: 3037
   targetPort: 3037
   protocol: TCP
 type: LoadBalancer