apiVersion: apps/v1
kind: Deployment
metadata:
  name: func
  labels:
    app: func
spec:
  replicas: 1
  selector:
    matchLabels:
      app: func
  template:
    metadata:
      labels:
        app: func
    spec:
      containers:
      - name: func
        imagePullPolicy: Always
        image: kevinztw/func
        ports:
        - containerPort: 3038